### ISSUE TITLE
ImportError: cannot import name 'Qwen2AudioForConditionalGeneration' from 'transformers' (/root/miniconda3/lib/python3.12/site-packages/transformers/__init__.py)

### ISSUE THREAD

**Issue by Anorid** [QwenLM/Qwen2-Audio#20]
在部署安装运行这个测试代码的时候报错了python demo/web_demo_audio.py
root@autodl-container-5df045955b-854daaac:~/autodl-tmp/Qwen2-Audio# python demo/web_demo_audio.py
Traceback (most recent call last):
  File "/root/autodl-tmp/Qwen2-Audio/demo/web_demo_audio.py", line 4, in <module>
    from transformers import AutoProcessor, Qwen2AudioForConditionalGeneration
ImportError: cannot import name 'Qwen2AudioForConditionalGeneration' from 'transformers' (/root/miniconda3/lib/python3.12/site-packages/transformers/__init__.py)
这是报错情况，我的transformers是4.4版本需要降低版本吗

**Comment by faychu** [comment]
您需要从源码安装transformers，参考：https://github.com/QwenLM/Qwen2-Audio?tab=readme-ov-file#requirements

**Comment by noleRise** [comment]
请问不能直接用git装transformers有其他解决方法吗？

**Comment by noleRise** [comment]
> 在部署安装运行这个测试代码的时候报错了python demo/web_demo_audio.py root@autodl-container-5df045955b-854daaac:~/autodl-tmp/Qwen2-Audio# python demo/web_demo_audio.py Traceback (most recent call last): File "/root/autodl-tmp/Qwen2-Audio/demo/web_demo_audio.py", line 4, in from transformers import AutoProcessor, Qwen2AudioForConditionalGeneration ImportError: cannot import name 'Qwen2AudioForConditionalGeneration' from 'transformers' (/root/miniconda3/lib/python3.12/site-packages/transformers/**init**.py) 这是报错情况，我的transformers是4.4版本需要降低版本吗

你好，我遇到了和你一样的问题，请问你找到解决方法了吗？

**Comment by Rudyonly1** [comment]
pip install git+https://github.com/huggingface/transformers

**Comment by allen-78-2** [comment]
可以从魔搭的模型文件页面下载：https://modelscope.cn/models/qwen/Qwen2-Audio-7B-Instruct/files

**Comment by AntyRia** [comment]
use `pip install git+https://github.com/huggingface/transformers` 
error:
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1659, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 50, in <module>
    from ..pytorch_utils import isin_mps_friendly
  File "/usr/local/lib/python3.10/site-packages/transformers/pytorch_utils.py", line 27, in <module>
    ALL_LAYERNORM_LAYERS = [nn.LayerNorm, nn.RMSNorm]
AttributeError: module 'torch.nn' has no attribute 'RMSNorm'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1659, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 46, in <module>
    from .generation import GenerationConfig, GenerationMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1649, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1661, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
module 'torch.nn' has no attribute 'RMSNorm'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1659, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 25, in <module>
    from ... import PreTrainedModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1649, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1661, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
module 'torch.nn' has no attribute 'RMSNorm'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/project/nlp_model/Qwen2_Audio/demo.py", line 4, in <module>
    from transformers import Qwen2AudioForConditionalGeneration, AutoProcessor
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1650, in __getattr__
    value = getattr(module, name)
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1649, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1661, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.qwen2_audio.modeling_qwen2_audio because of the following error (look up to see its traceback):
Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
module 'torch.nn' has no attribute 'RMSNorm'

`
