### ISSUE TITLE
ModelScopeMultimodalInput.__init__() got an unexpected keyword argument 'upload_button_props'

### ISSUE THREAD

**Issue by O-O1024** [QwenLM/Qwen2-Audio#36]
运行后 `python demo/web_demo_audio.py` 出错

```
Traceback (most recent call last):
  File "/root/Qwen2-Audio/demo/web_demo_audio.py", line 168, in <module>
    _launch_demo(args)
  File "/root/Qwen2-Audio/demo/web_demo_audio.py", line 124, in _launch_demo
    user_input = mgr.MultimodalInput(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/component_meta.py", line 160, in wrapper
    return fn(self, **kwargs)
TypeError: ModelScopeMultimodalInput.__init__() got an unexpected keyword argument 'upload_button_props'
```

**Comment by O-O1024** [comment]
使用 `pip install modelscope_studio==0.3.1` 可以

**Comment by TengfeiSong000** [comment]
为什么我安装到0.3.1版本还是不行

**Comment by ice-tong** [comment]
pip install http://thunlp.oss-cn-qingdao.aliyuncs.com/multi_modal/never_delete/modelscope_studio-0.4.0.9-py3-none-any.whl

可以解决问题，
